print ("Hi, my job is to compliment everything you do in the nicest way.")

name = input("What's your name? ")
print (name +"?!! That is the worst name I have ever heard of")
print ("")
age = input("How old are you? ")
print ("My grandma is 10 years younger than", age + ".")
print ("")
activities = input("""I am so sorry sometimes I burst,
anyway what do you do for fun? """)
print (activities + "? You think THAT is fun? That is the most boring thing ever")
print ("")
music = input("Sorry but it's true. What type of music do you listen to? ")
print ("You should destroy all of", music)
print ("")
siblings = input("Sorry " + music + " is kinda my trigger. How many siblings do you have? ")
print (siblings + "?! What is your family a freak show?")
print ("")
growUp = input("OK last chance for you not to be a loser. What do you want to be when you grow up? ")
print (growUp + "? Seriously? I'm out, you are a complete loser")
print ("")
print ("YA!!! How do you feel about that ROAST! I JUST ROASTED YOU!")
